apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      containers:
        - name: backend
          image: ghcr.io/consul-up/birdwatcher-backend:1.0.0
          env:
            - name: BIND_ADDR
              value: '0.0.0.0:7000'
            - name: TRACING_URL
              value: 'http://jaeger-collector.default:9411'
            - name: VERSION
              value: 'v1'
          ports:
            - containerPort: 7000
          readinessProbe:
            httpGet:
              port: 7000
              path: /healthz
            periodSeconds: 5
